'use client';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import dynamic from 'next/dynamic';
import { Box, CssBaseline, StyledEngineProvider, ThemeProvider } from '@mui/material';
import configs from '@/configs';
import Appbar from '@/components/layouts/Appbar';
import Sidebar from '@/components/layouts/Sidebar';

const WalletProvider = dynamic(() => import('@/providers/WalletProvider'), {
  ssr: false,
});

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledEngineProvider injectFirst>
        <ThemeProvider theme={configs.theme}>
          <body className={inter.className} suppressHydrationWarning={true}>
            <CssBaseline />
            <WalletProvider>
              <Appbar />
              <Box display="flex">
                <Sidebar />
                {children}
              </Box>
            </WalletProvider>
          </body>
        </ThemeProvider>
      </StyledEngineProvider>
    </html>
  );
}
